### ISSUE TITLE
dead references to libpdinstances prevent events from being called/instances never freed

### ISSUE THREAD

**Issue by fotocopiadora-69** [LibPdIntegration/LibPdIntegration#16]
libpdinstances added to the activeInstances list are never removed even if the instances themselves are destroyed or disabled, filling the list with dead references. in combination with this if statement
```
		if(this == activeInstances[0])
		{
			libpd_queued_receive_pd_messages();
			libpd_queued_receive_midi_messages();
		}
```
it causes pd and midi events to never be called unless the instance originally assigned at index 0 is still active. adding
```
	void OnDisable() {
		activeInstances.Remove(this);
	}
```
seems to fix the problem. however, it looks like actual instances (within libpd) are still never freed

**Comment by NiallMoody** [comment]
Ah, that's a really good point. I must have coded it on the assumption that LibPdInstance would be active for the duration of a scene, which is obviously wrong. I think the solution is to move all the instance-specific cleanup out of OnApplicationQuit and move it into OnDisable.

Plus, I should have been calling libpd_free_instance to free the libpd instances. That's a major oversight.

I'll try and put together a fix by the end of the week. Thanks for pointing this out.

**Comment by NiallMoody** [comment]
I've just committed those changes. If you can confirm it works for you I'll make it an official release.
