### ISSUE TITLE
Application.dataPath

### ISSUE THREAD

**Issue by karljj1** [LibPdIntegration/LibPdIntegration#3]
Hey. Nice library.
You have a bug where you use Application.dataPath, when you should be using Application.streamingAssetsPath.
It means that when you build it sometimes cannot find PD files.

**Comment by NiallMoody** [comment]
Hi! Sorry, I only just realised I didn't have notifications turned on for issues, and I'd completely missed this. I'm going to close this issue for now, as it seems to be tied up with [2018.3 issues with directories](https://github.com/LibPdIntegration/LibPdIntegration/issues/4). I should have some time in the next couple of weeks to investigate and figure out the best (cross-platform) solution.
